name: NanoGPT
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appnope=0.1.4
  - asttokens=3.0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - comm=0.2.3
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - debugpy=1.8.16
  - decorator=5.2.1
  - deprecated=1.2.18
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fsspec=2025.10.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - icu=75.1
  - importlib-metadata=8.5.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libabseil=20250814.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libcxx=20.1.8
  - libcxxabi=20.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.30
  - libprotobuf=6.33.0
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtorch=2.7.0
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - ocl-icd=2.3.3
  - openblas=0.3.30
  - opencl-headers=2025.07.22
  - openssl=3.6.0
  - opentelemetry-api=1.30.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.7.0
  - pytorch-cuda=12.1
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /anaconda/envs/NanoGPT
