name: NanoGPT
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.18=py310hca03da5_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.0=py310hca03da5_0
  - fsspec=2025.10.0=py310h7eb115d_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.2=py310hbcc4bda_0
  - importlib-metadata=8.5.0=py310hca03da5_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310hca03da5_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libopenblas=0.3.30=hf2bb037_2
  - libprotobuf=6.33.0=hff18ee8_0
  - libsodium=1.0.20=h99b78c6_0
  - libtorch=2.7.0=gpu_mps_h96286cc_201
  - libuv=1.48.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=3.0=0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.30.0=py310hca03da5_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pytorch=2.7.0=gpu_mps_py310h1211112_201
  - pyzmq=27.1.0=py310h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py310hca03da5_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py310h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310hca03da5_0
  - wrapt=1.17.0=py310h80987f9_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=py310hca03da5_0
  - zlib=1.3.1=h5f15de7_0
prefix: /opt/anaconda3/envs/NanoGPT
